DEFAULTS: &DEFAULTS
  adapter: mysql2
  host: localhost
  username: root
  password:
  port: 3306

#==================================================================================

development:
  database: s4s_dev
  <<: *DEFAULTS

test:
  database: s4s_test
  <<: *DEFAULTS

production:
  database: s4s
  username: s4s
  password: fluffy
  <<: *DEFAULTS

#==================================================================================
